import { isGeneratedPhotoFileName } from "./photo-storage";

/**
 * A file name is orphaned when it was generated by this app (so it is safe to remove)
 * but no wine references it any more. Foreign file names are left alone.
 */
export function findOrphanedPhotoFileNames(
  storedFileNames: string[],
  referencedFileNames: string[],
): string[] {
  const referencedFileNameSet = new Set(referencedFileNames);
  return storedFileNames.filter(
    (fileName) => isGeneratedPhotoFileName(fileName) && !referencedFileNameSet.has(fileName),
  );
}
